### ISSUE TITLE
vec_sll example

### ISSUE THREAD

**Issue by wschmidt-ibm** [OpenPOWERFoundation/Programming-Guides#24]
PC suggests an example of the vec_sll endian issue.  Not a show-stopper if this isn't done.

**Comment by ThinkOpenly** [comment]
Would this be better in section 2.5 _Vector Built-In Functions_ or section 4.2 _Built-In Vector Functions_?

**Comment by wschmidt-ibm** [comment]
I think 4.2, please.

**Comment by ThinkOpenly** [comment]
After thinking on this a bit, given the general compactness and fairly consistent presentation in 4.2, I think it would be awkward and perhaps more confusing than helpful to add a _bad_ example within the definition for `vec_sll`.
I would be more inclined toward adding a bad example in section 2.5 as an example of what happens if endianness is not accommodated for endian-sensitive intrinsics.
Or, perhaps this issue should just be closed, since all of the impacted intrinsics clearly say "This intrinsic is _not_ endian-neutral, so uses of `vec_sll` in big-endian code must be rewritten for little-endian targets."
Another option, after reading that quote again, is to put an example, perhaps in section 2.5, of how "code must be rewritten for little-endian targets", since this document provides no specific guidance. (In the entire document, the only uses of "swap" are in `vec_xl` and `vec_xst`.)

**Comment by wschmidt-ibm** [comment]
I think if you want to go that route, the more appropriate place is section 2.7, which is specifically for this purpose.

**Comment by wschmidt-ibm** [comment]
I honestly don't care whether or not we explain this, given that vec_sll is not a terribly useful interface.  vec_sl, vec_sld, and vec_slo are more sensible.

**Comment by wschmidt-ibm** [comment]
In fact, I would really lean towards closing this issue. :-D
